apiVersion: v1
appVersion: "latest"
description: Highly configurable Mqtt stresstester service with random data generation functionality
icon: https://raw.githubusercontent.com/davidjmallar/MqttZombie/master/docs/header.png
name: mqtt-zombie
version: 0.1.0
